// Code generated by mockery. DO NOT EDIT.

package commandsmocks

import (
	"basket-service/internal/core/application/usecases/commands"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AddDeliveryPeriodCommandHandlerMock is an autogenerated mock type for the AddDeliveryPeriodCommandHandler type
type AddDeliveryPeriodCommandHandlerMock struct {
	mock.Mock
}

type AddDeliveryPeriodCommandHandlerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AddDeliveryPeriodCommandHandlerMock) EXPECT() *AddDeliveryPeriodCommandHandlerMock_Expecter {
	return &AddDeliveryPeriodCommandHandlerMock_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: _a0, _a1
func (_m *AddDeliveryPeriodCommandHandlerMock) Handle(_a0 context.Context, _a1 commands.AddDeliveryPeriodCommand) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.AddDeliveryPeriodCommand) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddDeliveryPeriodCommandHandlerMock_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type AddDeliveryPeriodCommandHandlerMock_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 commands.AddDeliveryPeriodCommand
func (_e *AddDeliveryPeriodCommandHandlerMock_Expecter) Handle(_a0 interface{}, _a1 interface{}) *AddDeliveryPeriodCommandHandlerMock_Handle_Call {
	return &AddDeliveryPeriodCommandHandlerMock_Handle_Call{Call: _e.mock.On("Handle", _a0, _a1)}
}

func (_c *AddDeliveryPeriodCommandHandlerMock_Handle_Call) Run(run func(_a0 context.Context, _a1 commands.AddDeliveryPeriodCommand)) *AddDeliveryPeriodCommandHandlerMock_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.AddDeliveryPeriodCommand))
	})
	return _c
}

func (_c *AddDeliveryPeriodCommandHandlerMock_Handle_Call) Return(_a0 error) *AddDeliveryPeriodCommandHandlerMock_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AddDeliveryPeriodCommandHandlerMock_Handle_Call) RunAndReturn(run func(context.Context, commands.AddDeliveryPeriodCommand) error) *AddDeliveryPeriodCommandHandlerMock_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewAddDeliveryPeriodCommandHandlerMock creates a new instance of AddDeliveryPeriodCommandHandlerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAddDeliveryPeriodCommandHandlerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AddDeliveryPeriodCommandHandlerMock {
	mock := &AddDeliveryPeriodCommandHandlerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
