// Code generated by mockery. DO NOT EDIT.

package commandsmocks

import (
	commands "basket-service/internal/core/application/usecases/commands"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ChangeStocksCommandHandlerMock is an autogenerated mock type for the ChangeStocksCommandHandler type
type ChangeStocksCommandHandlerMock struct {
	mock.Mock
}

type ChangeStocksCommandHandlerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ChangeStocksCommandHandlerMock) EXPECT() *ChangeStocksCommandHandlerMock_Expecter {
	return &ChangeStocksCommandHandlerMock_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: _a0, _a1
func (_m *ChangeStocksCommandHandlerMock) Handle(_a0 context.Context, _a1 commands.ChangeStocksCommand) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.ChangeStocksCommand) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChangeStocksCommandHandlerMock_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type ChangeStocksCommandHandlerMock_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 commands.ChangeStocksCommand
func (_e *ChangeStocksCommandHandlerMock_Expecter) Handle(_a0 interface{}, _a1 interface{}) *ChangeStocksCommandHandlerMock_Handle_Call {
	return &ChangeStocksCommandHandlerMock_Handle_Call{Call: _e.mock.On("Handle", _a0, _a1)}
}

func (_c *ChangeStocksCommandHandlerMock_Handle_Call) Run(run func(_a0 context.Context, _a1 commands.ChangeStocksCommand)) *ChangeStocksCommandHandlerMock_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.ChangeStocksCommand))
	})
	return _c
}

func (_c *ChangeStocksCommandHandlerMock_Handle_Call) Return(_a0 error) *ChangeStocksCommandHandlerMock_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChangeStocksCommandHandlerMock_Handle_Call) RunAndReturn(run func(context.Context, commands.ChangeStocksCommand) error) *ChangeStocksCommandHandlerMock_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewChangeStocksCommandHandlerMock creates a new instance of ChangeStocksCommandHandlerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChangeStocksCommandHandlerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChangeStocksCommandHandlerMock {
	mock := &ChangeStocksCommandHandlerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
