// Code generated by mockery. DO NOT EDIT.

package commandsmocks

import (
	commands "basket-service/internal/core/application/usecases/commands"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ChangeItemsCommandHandlerMock is an autogenerated mock type for the ChangeItemsCommandHandler type
type ChangeItemsCommandHandlerMock struct {
	mock.Mock
}

type ChangeItemsCommandHandlerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ChangeItemsCommandHandlerMock) EXPECT() *ChangeItemsCommandHandlerMock_Expecter {
	return &ChangeItemsCommandHandlerMock_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: _a0, _a1
func (_m *ChangeItemsCommandHandlerMock) Handle(_a0 context.Context, _a1 commands.ChangeItemsCommand) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.ChangeItemsCommand) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChangeItemsCommandHandlerMock_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type ChangeItemsCommandHandlerMock_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 commands.ChangeItemsCommand
func (_e *ChangeItemsCommandHandlerMock_Expecter) Handle(_a0 interface{}, _a1 interface{}) *ChangeItemsCommandHandlerMock_Handle_Call {
	return &ChangeItemsCommandHandlerMock_Handle_Call{Call: _e.mock.On("Handle", _a0, _a1)}
}

func (_c *ChangeItemsCommandHandlerMock_Handle_Call) Run(run func(_a0 context.Context, _a1 commands.ChangeItemsCommand)) *ChangeItemsCommandHandlerMock_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.ChangeItemsCommand))
	})
	return _c
}

func (_c *ChangeItemsCommandHandlerMock_Handle_Call) Return(_a0 error) *ChangeItemsCommandHandlerMock_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChangeItemsCommandHandlerMock_Handle_Call) RunAndReturn(run func(context.Context, commands.ChangeItemsCommand) error) *ChangeItemsCommandHandlerMock_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewChangeItemsCommandHandlerMock creates a new instance of ChangeItemsCommandHandlerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChangeItemsCommandHandlerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChangeItemsCommandHandlerMock {
	mock := &ChangeItemsCommandHandlerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
