// Code generated by mockery. DO NOT EDIT.

package commandsmocks

import (
	"basket-service/internal/core/application/usecases/commands"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CheckoutCommandHandlerMock is an autogenerated mock type for the CheckoutCommandHandler type
type CheckoutCommandHandlerMock struct {
	mock.Mock
}

type CheckoutCommandHandlerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CheckoutCommandHandlerMock) EXPECT() *CheckoutCommandHandlerMock_Expecter {
	return &CheckoutCommandHandlerMock_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: _a0, _a1
func (_m *CheckoutCommandHandlerMock) Handle(_a0 context.Context, _a1 commands.CheckoutCommand) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.CheckoutCommand) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckoutCommandHandlerMock_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type CheckoutCommandHandlerMock_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 commands.CheckoutCommand
func (_e *CheckoutCommandHandlerMock_Expecter) Handle(_a0 interface{}, _a1 interface{}) *CheckoutCommandHandlerMock_Handle_Call {
	return &CheckoutCommandHandlerMock_Handle_Call{Call: _e.mock.On("Handle", _a0, _a1)}
}

func (_c *CheckoutCommandHandlerMock_Handle_Call) Run(run func(_a0 context.Context, _a1 commands.CheckoutCommand)) *CheckoutCommandHandlerMock_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.CheckoutCommand))
	})
	return _c
}

func (_c *CheckoutCommandHandlerMock_Handle_Call) Return(_a0 error) *CheckoutCommandHandlerMock_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CheckoutCommandHandlerMock_Handle_Call) RunAndReturn(run func(context.Context, commands.CheckoutCommand) error) *CheckoutCommandHandlerMock_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewCheckoutCommandHandlerMock creates a new instance of CheckoutCommandHandlerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCheckoutCommandHandlerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CheckoutCommandHandlerMock {
	mock := &CheckoutCommandHandlerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
