// Code generated by mockery. DO NOT EDIT.

package servicesmocks

import (
	"basket-service/internal/core/domain/model/basket"
	mock "github.com/stretchr/testify/mock"
)

// PromoGoodServiceMock is an autogenerated mock type for the PromoGoodService type
type PromoGoodServiceMock struct {
	mock.Mock
}

type PromoGoodServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *PromoGoodServiceMock) EXPECT() *PromoGoodServiceMock_Expecter {
	return &PromoGoodServiceMock_Expecter{mock: &_m.Mock}
}

// AddPromo provides a mock function with given fields: _a0
func (_m *PromoGoodServiceMock) AddPromo(_a0 *basket.Basket) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for AddPromo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*basket.Basket) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PromoGoodServiceMock_AddPromo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPromo'
type PromoGoodServiceMock_AddPromo_Call struct {
	*mock.Call
}

// AddPromo is a helper method to define mock.On call
//   - _a0 *basket.Basket
func (_e *PromoGoodServiceMock_Expecter) AddPromo(_a0 interface{}) *PromoGoodServiceMock_AddPromo_Call {
	return &PromoGoodServiceMock_AddPromo_Call{Call: _e.mock.On("AddPromo", _a0)}
}

func (_c *PromoGoodServiceMock_AddPromo_Call) Run(run func(_a0 *basket.Basket)) *PromoGoodServiceMock_AddPromo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*basket.Basket))
	})
	return _c
}

func (_c *PromoGoodServiceMock_AddPromo_Call) Return(_a0 error) *PromoGoodServiceMock_AddPromo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PromoGoodServiceMock_AddPromo_Call) RunAndReturn(run func(*basket.Basket) error) *PromoGoodServiceMock_AddPromo_Call {
	_c.Call.Return(run)
	return _c
}

// NewPromoGoodServiceMock creates a new instance of PromoGoodServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPromoGoodServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PromoGoodServiceMock {
	mock := &PromoGoodServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
