// Code generated by mockery. DO NOT EDIT.

package queriesmocks

import (
	queries "delivery-service/internal/core/application/usecases/queries"

	mock "github.com/stretchr/testify/mock"
)

// GetAllCouriersQueryHandlerMock is an autogenerated mock type for the GetAllCouriersQueryHandler type
type GetAllCouriersQueryHandlerMock struct {
	mock.Mock
}

type GetAllCouriersQueryHandlerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *GetAllCouriersQueryHandlerMock) EXPECT() *GetAllCouriersQueryHandlerMock_Expecter {
	return &GetAllCouriersQueryHandlerMock_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: _a0
func (_m *GetAllCouriersQueryHandlerMock) Handle(_a0 queries.GetAllCouriersQuery) (queries.GetAllCouriersResponse, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 queries.GetAllCouriersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(queries.GetAllCouriersQuery) (queries.GetAllCouriersResponse, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(queries.GetAllCouriersQuery) queries.GetAllCouriersResponse); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(queries.GetAllCouriersResponse)
	}

	if rf, ok := ret.Get(1).(func(queries.GetAllCouriersQuery) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllCouriersQueryHandlerMock_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type GetAllCouriersQueryHandlerMock_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - _a0 queries.GetAllCouriersQuery
func (_e *GetAllCouriersQueryHandlerMock_Expecter) Handle(_a0 interface{}) *GetAllCouriersQueryHandlerMock_Handle_Call {
	return &GetAllCouriersQueryHandlerMock_Handle_Call{Call: _e.mock.On("Handle", _a0)}
}

func (_c *GetAllCouriersQueryHandlerMock_Handle_Call) Run(run func(_a0 queries.GetAllCouriersQuery)) *GetAllCouriersQueryHandlerMock_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(queries.GetAllCouriersQuery))
	})
	return _c
}

func (_c *GetAllCouriersQueryHandlerMock_Handle_Call) Return(_a0 queries.GetAllCouriersResponse, _a1 error) *GetAllCouriersQueryHandlerMock_Handle_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GetAllCouriersQueryHandlerMock_Handle_Call) RunAndReturn(run func(queries.GetAllCouriersQuery) (queries.GetAllCouriersResponse, error)) *GetAllCouriersQueryHandlerMock_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewGetAllCouriersQueryHandlerMock creates a new instance of GetAllCouriersQueryHandlerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetAllCouriersQueryHandlerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetAllCouriersQueryHandlerMock {
	mock := &GetAllCouriersQueryHandlerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
