// Code generated by mockery. DO NOT EDIT.

package portsmocks

import (
	basket "basket-service/internal/core/domain/model/basket"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// BasketRepositoryMock is an autogenerated mock type for the BasketRepository type
type BasketRepositoryMock struct {
	mock.Mock
}

type BasketRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *BasketRepositoryMock) EXPECT() *BasketRepositoryMock_Expecter {
	return &BasketRepositoryMock_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, aggregate
func (_m *BasketRepositoryMock) Add(ctx context.Context, aggregate *basket.Basket) error {
	ret := _m.Called(ctx, aggregate)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *basket.Basket) error); ok {
		r0 = rf(ctx, aggregate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BasketRepositoryMock_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type BasketRepositoryMock_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - aggregate *basket.Basket
func (_e *BasketRepositoryMock_Expecter) Add(ctx interface{}, aggregate interface{}) *BasketRepositoryMock_Add_Call {
	return &BasketRepositoryMock_Add_Call{Call: _e.mock.On("Add", ctx, aggregate)}
}

func (_c *BasketRepositoryMock_Add_Call) Run(run func(ctx context.Context, aggregate *basket.Basket)) *BasketRepositoryMock_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*basket.Basket))
	})
	return _c
}

func (_c *BasketRepositoryMock_Add_Call) Return(_a0 error) *BasketRepositoryMock_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BasketRepositoryMock_Add_Call) RunAndReturn(run func(context.Context, *basket.Basket) error) *BasketRepositoryMock_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, ID
func (_m *BasketRepositoryMock) Get(ctx context.Context, ID uuid.UUID) (*basket.Basket, error) {
	ret := _m.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *basket.Basket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*basket.Basket, error)); ok {
		return rf(ctx, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *basket.Basket); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*basket.Basket)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BasketRepositoryMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type BasketRepositoryMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
func (_e *BasketRepositoryMock_Expecter) Get(ctx interface{}, ID interface{}) *BasketRepositoryMock_Get_Call {
	return &BasketRepositoryMock_Get_Call{Call: _e.mock.On("Get", ctx, ID)}
}

func (_c *BasketRepositoryMock_Get_Call) Run(run func(ctx context.Context, ID uuid.UUID)) *BasketRepositoryMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *BasketRepositoryMock_Get_Call) Return(_a0 *basket.Basket, _a1 error) *BasketRepositoryMock_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BasketRepositoryMock_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*basket.Basket, error)) *BasketRepositoryMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, aggregate
func (_m *BasketRepositoryMock) Update(ctx context.Context, aggregate *basket.Basket) error {
	ret := _m.Called(ctx, aggregate)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *basket.Basket) error); ok {
		r0 = rf(ctx, aggregate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BasketRepositoryMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type BasketRepositoryMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - aggregate *basket.Basket
func (_e *BasketRepositoryMock_Expecter) Update(ctx interface{}, aggregate interface{}) *BasketRepositoryMock_Update_Call {
	return &BasketRepositoryMock_Update_Call{Call: _e.mock.On("Update", ctx, aggregate)}
}

func (_c *BasketRepositoryMock_Update_Call) Run(run func(ctx context.Context, aggregate *basket.Basket)) *BasketRepositoryMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*basket.Basket))
	})
	return _c
}

func (_c *BasketRepositoryMock_Update_Call) Return(_a0 error) *BasketRepositoryMock_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BasketRepositoryMock_Update_Call) RunAndReturn(run func(context.Context, *basket.Basket) error) *BasketRepositoryMock_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewBasketRepositoryMock creates a new instance of BasketRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBasketRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *BasketRepositoryMock {
	mock := &BasketRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
