// Code generated by mockery. DO NOT EDIT.

package portsmocks

import (
	basket "basket-service/internal/core/domain/model/basket"
	context "context"

	kernel "basket-service/internal/core/domain/model/kernel"

	mock "github.com/stretchr/testify/mock"
)

// DiscountClientMock is an autogenerated mock type for the DiscountClient type
type DiscountClientMock struct {
	mock.Mock
}

type DiscountClientMock_Expecter struct {
	mock *mock.Mock
}

func (_m *DiscountClientMock) EXPECT() *DiscountClientMock_Expecter {
	return &DiscountClientMock_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *DiscountClientMock) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DiscountClientMock_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type DiscountClientMock_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *DiscountClientMock_Expecter) Close() *DiscountClientMock_Close_Call {
	return &DiscountClientMock_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *DiscountClientMock_Close_Call) Run(run func()) *DiscountClientMock_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DiscountClientMock_Close_Call) Return(_a0 error) *DiscountClientMock_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DiscountClientMock_Close_Call) RunAndReturn(run func() error) *DiscountClientMock_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetDiscount provides a mock function with given fields: ctx, _a1
func (_m *DiscountClientMock) GetDiscount(ctx context.Context, _a1 *basket.Basket) (kernel.Discount, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetDiscount")
	}

	var r0 kernel.Discount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *basket.Basket) (kernel.Discount, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *basket.Basket) kernel.Discount); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(kernel.Discount)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *basket.Basket) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DiscountClientMock_GetDiscount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDiscount'
type DiscountClientMock_GetDiscount_Call struct {
	*mock.Call
}

// GetDiscount is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *basket.Basket
func (_e *DiscountClientMock_Expecter) GetDiscount(ctx interface{}, _a1 interface{}) *DiscountClientMock_GetDiscount_Call {
	return &DiscountClientMock_GetDiscount_Call{Call: _e.mock.On("GetDiscount", ctx, _a1)}
}

func (_c *DiscountClientMock_GetDiscount_Call) Run(run func(ctx context.Context, _a1 *basket.Basket)) *DiscountClientMock_GetDiscount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*basket.Basket))
	})
	return _c
}

func (_c *DiscountClientMock_GetDiscount_Call) Return(_a0 kernel.Discount, _a1 error) *DiscountClientMock_GetDiscount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DiscountClientMock_GetDiscount_Call) RunAndReturn(run func(context.Context, *basket.Basket) (kernel.Discount, error)) *DiscountClientMock_GetDiscount_Call {
	_c.Call.Return(run)
	return _c
}

// NewDiscountClientMock creates a new instance of DiscountClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDiscountClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *DiscountClientMock {
	mock := &DiscountClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
