// Code generated by mockery. DO NOT EDIT.

package portsmocks

import (
	"basket-service/internal/core/domain/model/good"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// GoodRepositoryMock is an autogenerated mock type for the GoodRepository type
type GoodRepositoryMock struct {
	mock.Mock
}

type GoodRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *GoodRepositoryMock) EXPECT() *GoodRepositoryMock_Expecter {
	return &GoodRepositoryMock_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, aggregate
func (_m *GoodRepositoryMock) Add(ctx context.Context, aggregate *good.Good) error {
	ret := _m.Called(ctx, aggregate)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *good.Good) error); ok {
		r0 = rf(ctx, aggregate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GoodRepositoryMock_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type GoodRepositoryMock_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - aggregate *good.Good
func (_e *GoodRepositoryMock_Expecter) Add(ctx interface{}, aggregate interface{}) *GoodRepositoryMock_Add_Call {
	return &GoodRepositoryMock_Add_Call{Call: _e.mock.On("Add", ctx, aggregate)}
}

func (_c *GoodRepositoryMock_Add_Call) Run(run func(ctx context.Context, aggregate *good.Good)) *GoodRepositoryMock_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*good.Good))
	})
	return _c
}

func (_c *GoodRepositoryMock_Add_Call) Return(_a0 error) *GoodRepositoryMock_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GoodRepositoryMock_Add_Call) RunAndReturn(run func(context.Context, *good.Good) error) *GoodRepositoryMock_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, ID
func (_m *GoodRepositoryMock) Get(ctx context.Context, ID uuid.UUID) (*good.Good, error) {
	ret := _m.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *good.Good
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*good.Good, error)); ok {
		return rf(ctx, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *good.Good); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*good.Good)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GoodRepositoryMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type GoodRepositoryMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
func (_e *GoodRepositoryMock_Expecter) Get(ctx interface{}, ID interface{}) *GoodRepositoryMock_Get_Call {
	return &GoodRepositoryMock_Get_Call{Call: _e.mock.On("Get", ctx, ID)}
}

func (_c *GoodRepositoryMock_Get_Call) Run(run func(ctx context.Context, ID uuid.UUID)) *GoodRepositoryMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *GoodRepositoryMock_Get_Call) Return(_a0 *good.Good, _a1 error) *GoodRepositoryMock_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GoodRepositoryMock_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*good.Good, error)) *GoodRepositoryMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, aggregate
func (_m *GoodRepositoryMock) Update(ctx context.Context, aggregate *good.Good) error {
	ret := _m.Called(ctx, aggregate)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *good.Good) error); ok {
		r0 = rf(ctx, aggregate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GoodRepositoryMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type GoodRepositoryMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - aggregate *good.Good
func (_e *GoodRepositoryMock_Expecter) Update(ctx interface{}, aggregate interface{}) *GoodRepositoryMock_Update_Call {
	return &GoodRepositoryMock_Update_Call{Call: _e.mock.On("Update", ctx, aggregate)}
}

func (_c *GoodRepositoryMock_Update_Call) Run(run func(ctx context.Context, aggregate *good.Good)) *GoodRepositoryMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*good.Good))
	})
	return _c
}

func (_c *GoodRepositoryMock_Update_Call) Return(_a0 error) *GoodRepositoryMock_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GoodRepositoryMock_Update_Call) RunAndReturn(run func(context.Context, *good.Good) error) *GoodRepositoryMock_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewGoodRepositoryMock creates a new instance of GoodRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGoodRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *GoodRepositoryMock {
	mock := &GoodRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
