// Code generated by mockery. DO NOT EDIT.

package queriesmocks

import (
	"basket-service/internal/core/application/usecases/queries"
	mock "github.com/stretchr/testify/mock"
)

// GetBasketQueryHandlerMock is an autogenerated mock type for the GetBasketQueryHandler type
type GetBasketQueryHandlerMock struct {
	mock.Mock
}

type GetBasketQueryHandlerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *GetBasketQueryHandlerMock) EXPECT() *GetBasketQueryHandlerMock_Expecter {
	return &GetBasketQueryHandlerMock_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: _a0
func (_m *GetBasketQueryHandlerMock) Handle(_a0 queries.GetBasketQuery) (queries.GetBasketResponse, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 queries.GetBasketResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(queries.GetBasketQuery) (queries.GetBasketResponse, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(queries.GetBasketQuery) queries.GetBasketResponse); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(queries.GetBasketResponse)
	}

	if rf, ok := ret.Get(1).(func(queries.GetBasketQuery) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBasketQueryHandlerMock_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type GetBasketQueryHandlerMock_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - _a0 queries.GetBasketQuery
func (_e *GetBasketQueryHandlerMock_Expecter) Handle(_a0 interface{}) *GetBasketQueryHandlerMock_Handle_Call {
	return &GetBasketQueryHandlerMock_Handle_Call{Call: _e.mock.On("Handle", _a0)}
}

func (_c *GetBasketQueryHandlerMock_Handle_Call) Run(run func(_a0 queries.GetBasketQuery)) *GetBasketQueryHandlerMock_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(queries.GetBasketQuery))
	})
	return _c
}

func (_c *GetBasketQueryHandlerMock_Handle_Call) Return(_a0 queries.GetBasketResponse, _a1 error) *GetBasketQueryHandlerMock_Handle_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GetBasketQueryHandlerMock_Handle_Call) RunAndReturn(run func(queries.GetBasketQuery) (queries.GetBasketResponse, error)) *GetBasketQueryHandlerMock_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewGetBasketQueryHandlerMock creates a new instance of GetBasketQueryHandlerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetBasketQueryHandlerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetBasketQueryHandlerMock {
	mock := &GetBasketQueryHandlerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
